# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-FormValidator-Filters-HTMLScrubber
version:      0.02
version_from: lib/Data/FormValidator/Filters/HTMLScrubber.pm
installdirs:  site
requires:
    HTML::Scrubber:                0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
